name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository code
      - uses: actions/checkout@v3
        with:
          submodules: true  # If your theme is a Git submodule, this ensures it's cloned

      # 2) Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # or specify a version like '0.115.0'

      # 3) Build the site
      - name: Build
        run: hugo --minify

      # 4) Deploy to gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # The folder Hugo outputs to
          publish_branch: gh-pages
